AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.lulu::DataIntegrationPOC
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  DataIntegrationPOCFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.lulu.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: target/DataIntegrationPOC-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: json-csv-demo-bucket-123
      Timeout: 30
      Events:
        ApiTrigger:
            Type: Api
            Properties:
              Path: /{proxy+}
              Method: any

        ScheduledTrigger:
            Type: Schedule
            Properties:
              Schedule: rate(2 minutes)
Outputs:
  DataIntegrationPOCApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: DataIntegrationPOCApi
